[package]
edition = "2018"
name = "agent-tag-bevy"
version = "0.1.0"

[dependencies]
bevy = {version = "0.5.0", features = ["dynamic"]}
rand = {version = "0.8", features = ["small_rng"]}
structopt = "0.3"
